language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
# Django env
env:
  - DJANGO=1.6.1
  - DJANGO=1.6.2
# command to run tests
script:
  - python test.py